[options]
admin_passwd = admin
proxy_mode = True

db_host = dpg-d7br0redqaus73as2kkg-a.frankfurt-postgres.render.com
db_port = 5432
db_user = vibe_odoo_db_user
db_password = 1pzlftiECI121CR5IG1RUmwQ6fQSDDjk
db_name = odin_template

http_port = 8069
http_interface = 0.0.0.0


; Security
list_db = False

; Performance (requires Standard instance minimum)
workers = 1
gevent_port = 0
max_cron_threads = 1
db_maxconn = 15

; Memory (2GB instance)
limit_memory_soft = 1610612736
limit_memory_hard = 2040109465
limit_time_cpu = 60
limit_time_real = 120

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/usr/lib/python3/dist-packages/addons,/var/lib/odoo/custom_addons
